### PR TITLE
Upgrade hesabu and rules engine

### PR DESCRIPTION
**Pull request by pjaspers**
The aim of this PR is to be able to use `eval_array` and `array` in the Rails application.

```
eval_array('a', (1,2,3), 'b', (2,3,4), 'b - a')

'a'				=> key 1
'(1,2,3)'	=> array 1
'b'				=> key 2
'(2,3,4)		=> array 2 (needs to be same length as array 1)
'b-a'			=> metaformula

Will loop over the arrays and apply the formula to each index, so
in this example would result in:

      (2-1, 3-2,4-3)
      (1,1,1)
```

```
array(1,2,3,4,5)

A noop function in this context, mainly added for api parity with
dentaku, so arrays can be explicilty marked as arrays.

ARRAY(1,2,3) => (1,2,3,4,5)
```

This will allow us to use these kind of formulas:

```
        "arr" => "array(1,2,-3,4,5)",
        "evaled_arr" => "eval_array('a', arr, 'b', arr, 'a - b')",
        "result" => "sum(evaled_arr)"
```

And it will successfully calculate that `result` should be 0. A more concrete example will probably using `array` and `eval_array` in combination with `last_6_months_window_values` and storing those in a variable for more calculations.

 In order to use those:

- latest go-hesabu should be used (embedded in hesabu gem)
- latest git/master of hesabu should be used (dependency of orbf-rules_engine)
- latest git/master of orbf-rules_engine should be used

I've added a small spec to make sure that all these requirements are fulfilled.

As you can see (by the failing spec), at the moment it can't run eval_array for the version 2 engine.

This is because https://github.com/BLSQ/orbf-rules_engine/pull/41 is still open (so not yet in master). 'But why is the version 3 spec passing?', that's because I've changed the Gemfile to point to the latest hesabu git/master. So it will be able to use the latest go version. The `orbf-rules_engine` gem only has a dependency on `hesabu` it does not care about which version (we should fix that at some point), so by setting the version here, orbf-rules_engine is happy with the change and we can use the latest go-version.

## Self proof reading checklist

- [x] Did I run Pronto and fixed all warnings (pronto run -c origin/dev)
- [x] Make sure all naming and code will remain understandable in 6 month by someone new to the project or by you.
- [x] Did I test the right thing?

### CODE REVIEW

**Comment by mestachs** [comment]
merge the associated PR, you can update the Gemfile.lock

**Comment by mestachs** [comment]
you can perhaps add some function documentation for the end user in https://github.com/BLSQ/orbf2/blob/dev/app/views/setup/rules/_cheat_sheet_expression.html.erb

**Comment by pjaspers** [comment]
Added the functions to the cheat sheet, it now looks like this image

**Comment by mestachs** [comment]
I tried to paste the formula in the edit mode, but I'm getting
* `Formulas expression Undefined function eval_array `
* `Formulas Undefined function eval_array `

this is due to my duplication of the calculator in the gem
https://github.com/BLSQ/orbf2/blob/dev/app/services/rules/calculator_factory.rb#L4
vs
https://github.com/BLSQ/orbf-rules_engine/blob/master/lib/orbf/rules_engine/builders/calculator_factory.rb#L7

It looks the behaviour looks identic except the 2 added functions for this feature.
the only notable difference is the "options" provided to the `Dentaku::Calculator.new`

we can normaly keep

```ruby
module Rules
  class CalculatorFactory
     def new_calculator
         Orbf::RulesEngine::LegacyCalculatorFactory.build({})
     end
  end
end
```

once done the editition looks OK.

but the simulation fails with 

image

if there's a sum or avg operation, than it works

**Comment by pjaspers** [comment]
@mestachs I've fixed the calculator error (https://github.com/BLSQ/orbf2/pull/99/commits/00e13bce235941ff9c52bc531efb4418cc4ca5f5), I've also opened a PR on the rules engine to help with the formatting issue: https://github.com/BLSQ/orbf-rules_engine/pull/43/files

And I discovered a bug/edge case/feature in go-hesabu, which is fixed here: https://github.com/BLSQ/go-hesabu/pull/11

I think once we have these in, I can run the data tests and get this merged and to production.

**Pull request merged**
