### PR TITLE
ruby-2.5.1 -> ruby-2.5.8

### PR DESCRIPTION
**Pull request by pjaspers**
Mainly nothing to see here:

      https://github.com/ruby/ruby/compare/v2_5_1...v2_5_8

Mainly security and bug fixes.

I tested the performance by running the test suite on this laptop (2,8 GHz Dual-Core Intel Core i5 MacBook)

In 2.5.1: Finished in 4 minutes 55.6 seconds (files took 12.32 seconds
to load)
In 2.5.8: Finished in 4 minutes 55 seconds (files took 14.79 seconds to load)

Since I didn't run this a couple of times in a row, it's not much of a benchmark. But I think the performance is roughly the same.

### CODE REVIEW

**Comment by mestachs** [comment]
shouldn't we do all projects ?
   - https://github.com/BLSQ/orbf-rules_engine
   - https://github.com/blsq/hesabu

**Comment by pjaspers** [comment]
Yes. Should have made this one draft. Until the others are tested in multiple rubies.

**Comment by pjaspers** [comment]
Hesabu runs on 2.5.8 fine: https://travis-ci.org/github/BLSQ/hesabu/jobs/712427500

**Comment by pjaspers** [comment]
Made a pr to check for the rules engine on 2.5.8: https://github.com/BLSQ/orbf-rules_engine/pull/68

**Comment by pjaspers** [comment]
@mestachs I think the move to 2.5.8 can be done (timings don't look any better or worse than 2.5.1)

For 2.6 and 2.7, the rules engine needs some work to avoid regressions in performance.

**Pull request merged**
