### PR TITLE
Fix issues we had during async

### PR DESCRIPTION
**Pull request by pjaspers**
I deployed the async version on staging and during testing of that I ran into these issues:

- Projects sometimes didn't have a token set
- Jobs without a state were considered 'alive' (which was wrong)
- Error handling was not that great (now showing actual errors)
- Errors during simulation now bubble up to the user
- ActiveJob used its own async instead of sidekiq
- Cleaned up bootstrap script to include yarn

### CODE REVIEW

**Comment by pjaspers** [comment]
I'm not madly in love with the `alive?` method. It feels weird that I need to explicitly tell it that new jobs are not considered alive.

**Comment by mestachs** [comment]
the alive attribute was to move the condition on "should we keep the spinner" on the backend and allow to have extra status without breaking clients.

for the alive, the invoice generation put them with "enqueued" by default. 
https://github.com/BLSQ/orbf2/blob/dev/app/controllers/api/invoices_controller.rb#L24

**Comment by pjaspers** [comment]
Yes, doing that now. But it felt weird to 'cheat' in the tests. On the one hand I just want to set a default status of 'enqueued' on the other hand, this also feels like a lie.

**Comment by mestachs** [comment]
back to 90% !

**Pull request merged**
